- source/_static/js/custom.js
- source/conf.py
The updates add the items as shown in the image:
The "Need help? Click here." will take the user to the getting help/support page.  The "RDHPCS Home Page" will take the user to the [OCIO's HPCC page](https://www.noaa.gov/information-technology/hpcc).
> Add links to support page and RDHPCS home page

- .github/workflows/publish_docs.yml
This is to allow the build to run for PRs.  Also protect the deploy for only push events to the main branch
This is needed to ensure the build status can be reviewed before merging the PR from collaborators.
Fixes #33
> Updated the build/deploy workflow

- .github/workflows/publish_docs.yml
This is to stop the deploy from attempting in forks, as additional items are needed for the deploy to succeed in a fork.
fixes #55
> Deploy to not run on forks

- source/logging_in/index.rst
Common docs link removed
Reference added to Tectia page, Port Tunneling	
-- TODO note removed; replaced with link to Port Tunneling
> links corrected and updated

- requirements.txt
- source/_search/google64634d0922861b1a.html
- source/_search/robots.txt
- source/conf.py
Google needs the google*.html file to index the site.  The build process will also create a sitemap file in a location that is defined in the robots.txt file.
This needs to be merged before #86 so we know Google is indexing the site.
> Add required items for Google to index the site

- source/conf.py
This adds additional sphinx_sitemap configurations to source/conf.py to avoid including the localization information in the URL path.
> Remove the localization from the sitemap URL paths

- source/queue_policy/policies.rst
- source/systems/gaea_user_guide.rst
I had neglected to transfer Allocations and Quotas information to the git site. That's done now. I added this topic to the Policies page. If there's a better place for it, I'll be happy to put it there.
> adding Allocation and Quota material to Policies pages

- source/contributing/via_cli/index.rst
spoke with @underwoo about the following:
- the "Contributing via CLI" article referred to a list of Python packages, not the "requirements.txt" file
- @underwoo mentioned it would be better to have the `pip3 install` command reference the file
- this allows the team to add packages to the file, without having to remember to update the article
- the instructions were also moved to a later point in the article
- now, the user will have already "changed directory" into the cloned repo, and the path to "requirements.txt" will be correct
- also, added a GitHub link to the "requirements.txt" file, so any user can see what packages will be installed, even before cloning the repo
> update "Contributing via CLI"

- source/queue_policy/policies.rst
resolves issue #197, responding to Support Team (Gyorgy and Rahgu, separately) reporting that scrontab information was hard to find. It now follows Cron information in Policies file. If it needs to be someplace else, please tell me where explicitly.
> adding scrontab material to Policies

- source/systems/hera_user_guide.rst
Having removed the Hera QOS tables from Running and Monitoring Jobs, I have added them to the Hera UG.
> added QOS tables to Hera User Guide

- source/help/index.rst
- source/systems/MSU-HPC_user_guide.rst
After reviewing these two doc files with more senior team members, we noticed that there were some discrepancies between "MSU's stated policy regarding role accounts" and the docs.
This commit seeks to amend the docs in order to be in line with MSU's stated policies, and has been reviewed and approved by the senior team members from the meeting.
The commit also adds a line to the e-mail list on the "Getting Help" page to include the separate Hercules help desk e-mail address.
> updated "MSU role accounts"

- source/systems/cloud_user_guide.rst
This change to lines 352-359 of the Cloud UG adds a link to yesterday's Office Hours presentation.
> update Cloud Office Hours

- .readthedocs.yaml
- source/_templates/search.html
Once in place, this can be used to:
* Show PR builds
* Compare RTD search to Google search
> Build/host documentation on readthedocs.org

- source/systems/MSU-HPC_user_guide.rst
Fixed some cases of `#` that should have been `-`
> Fix typo in some MSU host names

- .github/CODEOWNERS
@DV-NOAA should be the owner of the following pages:
/source/accounts
/source/systems/hera_user_guide.rst
/source/systems/jet_user_guide.rst
/source/systems/niagara_user_guide.rst
/source/systems/msu-hpc_user_guide.rst
/source/data/nescc_hpss.rst
Fixes #239
> Add @DV-NOAA as owner of pages

- source/systems/MSU-HPC_user_guide.rst
after speaking with the team at MSU, we were advised to change the verbiage of the "password reset" section.
For context:
- MSU no longer uses the phone number as a way to reset passwords
- MSU advised that the self-serve "password reset" function on the TAPS portal should work in all cases besides "locked and disabled accounts"
- in the case of "locked and disabled accounts", the user should be directed to send a ticket to the help desk
> updated "MSU password reset"

- source/data/summary.rst
The help desk received a ticket with a user asking about the storage quotas of user home directories on Hera.
Upon review, it has been determined that the values for Hera, Jet, and Niagara are 5GB (not 50GB). Gaea is the only system with a 50GB storage quota.
This commit revises the values for Hera, Jet, and Niagara.
> adjusted "storage quotas of user home directories" on HPC systems

- source/software/workflows/cron/index.rst
The original PR (#241) to address the issue (#233) did not include this section.
Raghu and I were speaking on a Google call, and we wanted to add this section on "viewing currently running crontab processes".
This is because viewing scrontab processes is different than viewing crontab processes.
> adjusting "crontab" section re: viewing currently running processes (#233)

- source/software/python/jupyter.rst
This commit addresses some concerns that were discovered while working with a user.
First, it was noted that Jupyter Lab can assign the user a different port than the one specified. This occurs if the user gives Jupyter a port that is already occupied. In this case, Jupyter increments the port until it finds an available port. Then, if the user is unaware of the port change, the second SSH tunnel command will fail.
Second, the user continued to experience issues when tunnelling, which were successfully addressed by specifying the IPv4 loopback address of `127.0.0.1`, instead of using `localhost`. When using `localhost`, the system's host file can choose to resolve the hostname by using the IPv6 loopback address (`::1`). For some users, the IPv6 address will cause attempted connections to …
> updated the "Jupyter on RDHPCS" guide

- source/help/index.rst
as per Forrest's request, this commit adds a link to the "ticket user portal" so the doc readers can have easy access.
> added a link to the RDHPCS Help Ticket System User Portal

- README.md
Fix link on README page to point to our docs, and not OLCF
> #316 - fix link on README.md

- source/FAQ/index.rst
The instructions tell the user to go to AIM but doesn't include the URL.  This change is to include the URL so that users can navigate to the site.
Reference: OTRS: https://helpdesk.rdhpcs.noaa.gov/otrs/index.pl?Action=AgentTicketZoom;TicketID=54160#515186
> Include the URL for AIM

- source/FAQ/index.rst
Removed Python as a sub-section, I don't think that was intended.
Also add a link to the spack-stack documentation.
> Include spack-stack doc link and remove the sub-section Issue #347

- source/data/summary.rst
Now we have Ursa filesystems scratch3/4 available and DTNs are also available, so these need to be added to the documentation. This is issue #353
> Add information for Ursa DTNs

- source/systems/hera_user_guide.rst
These sections had not been updated for a while now.  We have a new QOS for windfall jobs that require the GPU resources.  
Some other minor fixes were done because PGI compiler is now NVHPC compiler.
> Update for slurm changes - replace windfall with gpuwf

- source/systems/cloud_user_guide.rst
Updated the FAQs with instructions to copy on AWS without authentication keys.
For reviewers:
- I put this information as a sub-subsection to AWS Lustre explained. If you've got a better idea I can move it.; but please be explicit.
- The command sequence looks plausible to me, that's not the same thing as "correct", so please make sure I've got this right
> Cloud FAQ update for issue 352

- source/help/index.rst
As the commit title states, this was a simple addition to the help desk e-mail table to include an e-mail address for the new Ursa HPC system.
This was a request by Forrest.
> added the Ursa help desk e-mail to the e-mail table

- source/connecting/index.rst
> Change the CAC bastion DNS names for Ursa/Mercury to have "-cac"

- .vscode/dicts/projWords.txt
- source/systems/gaea_user_guide.rst
Fixes #422 
Removed references to intel-classic and intel-oneapi
> Update Gaea UG - remove intel-classic and intel-oneapi module references

- .vscode/dicts/projWords.txt
- source/data/globus_online_data_transfer.rst
Fixes Issue #441 
adds manual line breaks to Gaea, Jet, Mercury and Niagara lines
> correct line breaks in Globus Collection table

- .vscode/dicts/projWords.txt
- source/queue_policy/policies.rst
- source/slurm/overview.rst
Fixes Issue #450 
The "Specifying Partitions and QOS" section of the Slurm overview refers to "the table above", but the table itself is missing.  The table in question appears in the Changing QOS’s section of the Policies and Best Practices chapter.
I created a link to the QOS table in the Changing QOS section.
> added a link to QOS table

- source/data/transferring_data.rst
Trusted DTN table is correct but users could need more information. Link to the comprehensive Collection table will get them there.
> adding a link to further Globus information

- source/index.rst
Keep the extra text in `system/index.rst`, but only print "systems" in the sidebar.
Fixes #519
> Change the sidebar to remove "NOAA RDHPCS" from the "systems" tab

- source/systems/hera_user_guide.rst
Hera’s /scratch1 and /scratch2 are going away!. Users need to migrate their files to /scratch3 and /scratch4.
We've added this information to the top of the Hera UG, with a link to a presentation with information and procedure.
> Changes to Hera User Guide supporting file migration

- source/software/index.rst
- source/software/python/index.rst
This adds a note to let users know that on Gaea the python modules do not include conda.
> Add information for Gaea to indicate the python modules do not include conda

- source/systems/cloud_user_guide.rst
- source/systems/index.rst
The Systems Landing Page contains a table with system names, which link to the NOAA HPCC page (https://www.noaa.gov/information-technology/hpcc) with basic site information. Several links in that table were broken (and it appears to me that the target links have been changed for what that's worth.)
The PR corrects the broken links.
Adding Seth and Eric for awareness.
> correct broken links on Systems Landing Page

- source/accounts/role_accounts.rst
The HPC admin team strictly controls which superuser commands can be run by users.
Users running `sudo su -l` will encounter issues, because users do not have permission to run `su -l`.
However, users *are* permitted to run `sudo su - <ROLE_ACCOUNT>`.
Therefore, this commit corrects the command that users should run to switch users to a role account.
> UPDATE: revised command to switch user to role account

- source/data/transferring_data.rst
Fixes Issue #585 
RDHPCS#2025080754000156
A user had a problem with the information in the Untrusted Data Transfer Nodes table. The table is too wide for the screen (there's a slider) and she just missed the "Directory as seen on the uDTN" column.
We're adding a alert so readers know that column is there for Mercury and Ursa.
> Added Attention below uDTN table

- source/connecting/index.rst
Initially it was thought "jet" was an alias for "bastion-jet" but that is true only for the Princeton bastion and not the Boulder bastion.  Best to fix the documentation.
The context is this ticket:
https://helpdesk.rdhpcs.noaa.gov/otrs/index.pl?Action=AgentTicketZoom;TicketID=58127
> Fix Jet CAC bastion hostnames in the table
