NOAA-RDHPCS/noaa-rdhpcs.github.io

- source/systems/gaea_user_guide.rst
Changes to following Sections:
System Overview
- C5 Nodes and Cores: Additional information on nodes and cores (specific to C5)
Compiling
- New Compilers on C5: Additional compiling Information specific to C5
- Shared Libraries
Known Issues
- Known Module Incompatibility 
- Executables from C3/C4 on C5
Additional section dedicated to Modules and Software
Changes 'cores per socket' on C5
> Updated Gaea User Guide with C5 system information

- CODE_OF_CONDUCT.md
- CODE_STYLE.md
- CONTRIBUTING.md
Add repository guide files for contributing, style and code of conduct.
No changes to the documentation.
> Add Contributing, style, and code of conduct guides

- source/software/python/conda_basics.rst
- source/software/python/cupy.rst
- source/software/python/index.rst
- source/software/python/jupyter.rst
- source/software/python/miniconda.rst
- source/software/python/parallel_h5py.rst
Fact checking for the systems is needed.  Some of the information is not true (is conda really on all systems).  For some of the incorrect data, we will need to correct the systems to match the documentation.
Partially resolves #29.
> Updated the python documentation

- .github/CODEOWNERS
> Initial CODEOWNERS file

- source/slurm_tips/index.rst
Updated Slurm page and added additional info from other RDHPCS  
#13
> Gather slurm documentation from all RDHPCS wikis, combine into a document for this site.

- .vscode/launch.json
- .vscode/tasks.json
Add a build and debug task to help with development of the software with Microsoft's Visual Studio Code.
Closes  #42.
> Add build and debug tasks for vscode

- .vscode/tasks.json
Adjusted the build task for windows systems.
> Fix fix build for windows systems.

- .github/workflows/link_check.yml
- .github/workflows/rst_lint.yml
- .vscode/tasks.json
- Makefile
- requirements.txt
- source/data/gfdl_archive.rst
- source/data/nescc_hpss.rst
- source/data/summary.rst
- source/help/index.rst
- source/help/maintenance.rst
- source/queue_policy/policies.rst
- source/software/python/conda_basics.rst
- source/software/python/index.rst
- source/software/python/jupyter.rst
- source/software/python/miniconda.rst
- source/software/python/parallel_h5py.rst
Updated Niagara User Guide; resolved warnings, can see the updated text in my terminal. Need to apply changes and publish, rather than have the updates vanish.
> Niagara UG Revision

- source/help/index.rst
This will need a further style edit. The passive voice is too well regarded in documentation writing. Gerunds too.
> edit style and broken links

- source/data/gfdl_archive.rst
- source/data/globus_example.rst
- source/data/index.rst
> info in two places

- source/data/globus_online_data_transfer.rst
- source/systems/cloud_user_guide.rst
A temporary message indicating the globus endpoints for the cloud are disabled was added.
> Add message to Cloud system documentation concerning Globus

- source/systems/cloud_user_guide.rst
In both  Office Hours and Training sections, I added a link to recorded training videos.
> two additions to Office Hours/Training

- source/accounts/index.rst
> Update accounts file

- source/systems/cloud_user_guide.rst
Corrected line breaks, started the Montly Utilization section, one target file
> Updates to Cloud page

- source/systems/HSMS_user_guide.rst
- source/systems/MSU-HPC_user_guide.rst
- source/systems/common.rst
- source/systems/gaea_user_guide.rst
- source/systems/hera_user_guide.rst
- source/systems/jet_user_guide.rst
- source/systems/niagara_user_guide.rst
- source/systems/pan/index.rst
This PR contains the fixes to the systems directory files so they pass the lint test.  
This partially addresses #91.
> Fixes for System folder to pass lint test

- .vscode/settings.json
- source/accounts/index.rst
Edited for line length and heading consistency
> Fix accounts/index to pass lint test

- source/software/ssh_clients/Tectia/index.rst
Met with Raghu Reddy and opened Issue#135. This PR will correct the target link for Tectia for all three OS
Fixes #134 and #135
> Issue #135 and issue #134 - correct Tectia target link

- source/conf.py
- source/systems/cloud_user_guide.rst
Improving Cloud page appearance (tabs); partly because it was needed, partly in support of Cloud account issues directed to this page.
> cloud: clean up appearance, numbered FAQ sections

- source/systems/MSU-HPC_user_guide.rst
#153 - add missing details from MSU account renewal page
> #153 - MSU updates from Wiki

- source/FAQ/index.rst
- source/systems/cloud_user_guide.rst
This corrects two broken links related to PR#161 and #163. If there are link failures with this submission I will address immediately
> corrected broken links related to PR161 and 163

- source/accounts/about_accounts.rst
- source/getting_started/index.rst
- source/software/python/x2go
hoping to clear all linting and other errors.
> further changes to getting started

- source/help/index.rst
- source/systems/common.rst
closes #193  Personally vs Personal, and incorrect |replacestring| usage.
> fix(#193): typos in systems/common and help

- source/FAQ/index.rst
- source/systems/cloud_user_guide.rst
updated Cloud and RDHPSC FAQ sections with links to recent Office Hours recordings
> updated office hours and Cloud office hours

- source/connecting/index.rst
> fix(#202): macro fixing for bastion hostnames

- source/systems/jet_user_guide.rst
removed the QOS table from the Running and Monitoring section, and added same to the Jet User Guide.
> added Jet table to Jet User Guide

- source/FAQ/index.rst
- source/accounts/accounts_and_projects.rst
- source/connecting/index.rst
As from Unni, with minor updates.
Closes #208
> FAQ update for cloud on-prem user access issue

- source/slurm/overview.rst
Closes #214 
Takes care of some of #188 items.
> fix(#214): add module details to slurm overview

- source/accounts/rsa_software_token.rst
As per recent RSA updates, adjusting documentation to reflect new reality.
closes #209
> update the rsa activation pieces

- source/data/globus_example.rst
- source/software/x2go.rst
- source/systems/cloud_user_guide.rst
Adds the link and tidies some broken links.
> adds link to Parallel Works for On Prem

- source/accounts/rsa_software_token.rst
closes #218 
add in the step to request a token.
> fix(#218) update the rsa token steps

- .readthedocs.yaml
- source/_templates/search.html
- source/connecting/index.rst
- source/queue_policy/policies.rst
- source/software/containers/index.rst
- source/software/index.rst
- source/software/x2go.rst
- source/systems/cloud_user_guide.rst
- source/systems/hera_user_guide.rst
- source/systems/jet_user_guide.rst
This includes a previously missed page on containers
> Fixes broken links hit after redirect of old wiki sites, adds containers and rtd foundations

- source/systems/cloud_user_guide.rst
per Raghu's request, added a FAQ item for a user getting quota messages when working on the on-prem system.
Note that this is added at the end of the Parallel Works section. Note also that it follows a Parallel Works on-prem question that may be outdated, please check me on that.
> added item about on-prem quota to Cloud FAQ

- source/FAQ/index.rst
Adding a link to the training recording and transript.
> recording and transript for 9/20 office hour

- .vscode/settings.json
- README.md
> Fixed link in README.md

- source/systems/cloud_user_guide.rst
Adds Q and A for cloud login error to FAQ session, resolves Issue #246 
Adding Unni for awareness.
> issue #246 add login error Q/A

- source/conf.py
This is required per #249.
fixes #249
> Remove mermaid form build requirements

- source/systems/hera_user_guide.rst
per earlier discussion. Also want to see if I got the numbering thing right.
> Link Ursa/Rhea presentation to Hera page

- source/accounts/role_accounts.rst
Closes #187.  Adjusts page to be more general and accurate.
> Update role account page

- .github/CODEOWNERS
#272 - update CODEOWNERS file to provide multiple owners for /source files without specific assignees
> #272 - update CODEOWNERS config to prevent PR issues

- source/data/globus_example.rst
- source/systems/cloud_user_guide.rst
Created Parallel Works chapter per issue #256 
incorporating comments to draft from Unni. 
Note that material from FAQ has hyperlinked section titles to make it easier to forward to users. 
Note that incorrect information about expired RSA tokens has been removed per Issue #229
> updated Cloud UG, parallel works section

- source/data/globus_example.rst
Separating out the bits of PR270 to move matters along. This is the Globus Example revision.
> revised Globus example per instructions from Raghu

- source/systems/cloud_user_guide.rst
#280 #282 - combining clouse_user_guide changes - replacing PR's #281 and #283
> #280 #282 - combining cloud_user_guide changes

- source/data/transferring_data.rst
I've verified that the broken link works, at least it did yesterday
> Issue #287 - transferring_data updates

- source/queue_policy/policies.rst
#274 - Fix URL for On-Premises Allocation Request Form
> #274 - Fix URL for On-Premises Allocation Request Form

- .github/CODEOWNERS
#298 - update CODEOWNERS to remove Seth & Dave
> #298 - update CODEOWNERS to remove Seth & Dave

- source/accounts/accounts_and_projects.rst
Lisa Rizzo requested that this language be added to the Reactivate portion of the Accounts page.
> adding reactivate instructions

- source/accounts/accounts_and_projects.rst
- source/accounts/rsa_token.rst
See Issue #302 for details. Lisa's been getting a bunch of tickets on the same account problems, let's see if this helps with that.
> adding clarity to RSA and Project steps

- source/systems/gaea_user_guide.rst
Add GPFS Compression details per #278 
@underwoo - looking to you in particular for review, to ensure you're happy with the info is constructed on the page...
> #278 - Add GPFS Compression details

- source/data/globus_online_data_transfer.rst
This is previous content that was missing in the update pages. The text slightly edited for style and clarity.
> Sharing with External Collaborators

- source/systems/jet_user_guide.rst
removing lfs4 information, added lfs6, changed features per Forrest.
> update Jet system features

- source/systems/gaea_user_guide.rst
Updated the C6 information.
Closes #338
> Updated C6 information

- source/data/transferring_data.rst
> Update transferring_data.rst to include Ursa DTN and uDTNS

- source/data/globus_online_data_transfer.rst
Update Globus endpoint information for Ursa 
Issue #357
> Update Globus endpoints for Ursa

- source/data/globus_example.rst
Add Ursa to the Globus example page
Issue #359
> Add Ursa to the Globus example page

- source/FAQ/index.rst
> Add Ursa DTN information to the Recent User Facing Changes

- source/systems/cloud_user_guide.rst
Added two Q&A at the end of General Issues (just before Parallel Works, to make your search easier). Once again, if there's a better place for it, let me know and I'll move these items.
> added Case #340 to Cloud FAQ

- source/software/modules/index.rst
at Halle's suggestion, raised the Command Summary to a section, so the title appears in the sidebar for Modules.
> Command Summary in Modules file

- source/data/nescc_hpss.rst
> data HPSS page, update Gaea info

- .vscode/dicts/PythonConda.txt
- source/software/python/index.rst
This improves the text in the last two sections of the main python page.
References #324
> Finished main python page with updates

- source/data/globus_online_data_transfer.rst
- source/data/transferring_data.rst
Suggested rewrite and small changes (including a comma)
> edits from Aparna

- source/data/globus_example.rst
- source/data/globus_online_data_transfer.rst
I'm breaking out the changes into new clean branches.
> changes to Globus files only

- source/slurm/overview.rst
Raghu requested specific material be added; it's a level of direction his users need.
> add interactive job material

- source/software/workflows/rocoto/index.rst
- source/systems/MSU-HPC_user_guide.rst
- source/systems/gaea_user_guide.rst
- source/systems/hera_user_guide.rst
- source/systems/niagara_user_guide.rst
> Labelling Changes

- source/data/globus_online_data_transfer.rst
* Remove duplicate lines.
* Remove `======` formatting.
> docs:  fix formatting in globus_online_data_transfer.rst

- .github/CODEOWNERS
#409 - remove @josh-eisinger from CODEOWNERS file
> #409 - remove Josh from CODEOWNERS file

- source/systems/mercury_user_guide.rst
> Update purging period and uDTN access directory

- source/FAQ/index.rst
- source/accounts/rsa_token.rst
- source/data/globus_online_data_transfer.rst
- source/software/debuggers/index.rst
- source/software/python/conda_basics.rst
- source/software/python/index.rst
- source/systems/cloud_user_guide.rst
- source/systems/jet_user_guide.rst
> Add Mercury endpoints to the Globus collections table

- .vscode/dicts/projWords.txt
- source/FAQ/index.rst
- source/index.rst
Fixes #416
Fixes #430 
Issue #416 caught an organizational error -- several general questions and answers mixed with Port Tunneling questions. I corrected the title to User Questions, removed the material from Port Tunneling and put it where it belonged.
Issue #430 observed that two answers were squashed together. Added a new question to separate the two answers correctly.
> FAQ organization and correction

- source/data/globus_online_data_transfer.rst
> globus_online_data_transfer.rst: change collection summary to a table vs tabbed layout

- source/data/globus_online_data_transfer.rst
- source/queue_policy/policies.rst
Corrected path under Hera for file systems.
> Hera path correction for Globus table

- source/data/globus_online_data_transfer.rst
Fixes issue #444 
Corrections from Gyorgy Fekete to Jet entry in Globus Collections Summary table
> corrections to Jet entry in Collections table

- source/systems/cloud_user_guide.rst
Fixes #446 
Issue requests link to PW repository for directions to automate clusters in PW. 
This branch also corrects some small errors in spelling, punctuation and grammar.
> Add Automate Clusters link to PW repo

- source/queue_policy/policies.rst
Responds to #456 
Nikki Ivie created an updated QOS table, including Ursa, Jet and Hera values.
Per her request I've removed the old table and replaced it with the updated table in the same place.
> Update QOS table

- source/queue_policy/policies.rst
changed gpu wording from partition to QOS. Updated links under Fairshare to point to Priority and Fairshare documentation
> Update Jet/Hera/Ursa table

- source/systems/hera_user_guide.rst
remove barking link from Hera user guide
> consistent linkcheck failure

- .vscode/dicts/projWords.txt
- source/systems/common.rst
- source/systems/index.rst
- source/systems/ursa_user_guide.rst
Addresses #463 
Updates Connecting section.
> Update location and systems

- source/queue_policy/policies.rst
- source/systems/ursa_user_guide.rst
Corrected the compute name partition from ``u1`` to ``u1-compute``
Added a ``long`` QOS row to the QOS table
> Update partitions and QOS tables

- source/queue_policy/policies.rst
- source/systems/ursa_user_guide.rst
Not sure how Lis's changes got lost, but we also changed the text a little.
> Fix Ursa file systems section

- source/systems/ursa_user_guide.rst
Added more clarification to this section
> Revise the software stack section

- source/data/nescc_hpss.rst
> add note about 3TB files in HPSS

- source/accounts/rsa_token.rst
Lisa Rizzo requested wording changes to the instructions to obtain an RSA token -- she's been getting questions. She believes these changes will help with that.
> Corrections to RSA token instructions

- source/systems/cloud_user_guide.rst
Added "Can I Prevent Runaway Cloud Expenses?" to the Cloud FAQ. 
It appears as the last item in the Clusters section.
> New topic for Cloud FAQ

- source/queue_policy/policies.rst
Undo some inadvertent changes to the QOS table and also do some minor formatting fixes
> Undo some inadvertent changes to the QOS table

- .vscode/dicts/NOAA.txt
- .vscode/dicts/projWords.txt
- source/accounts/accounts_and_projects.rst
- source/accounts/rsa_token.rst
- source/conf.py
- source/connecting/index.rst
- source/contributing/index.rst
- source/data/globus_example.rst
- source/data/globus_online_data_transfer.rst
- source/data/local_migration.rst
- source/data/nescc_hpss.rst
- source/data/summary.rst
- source/data/transferring_data.rst
- source/queue_policy/policies.rst
- source/slurm/overview.rst
- source/slurm/shpcrpt.rst
- source/software/modules/index.rst
- source/software/python/miniforge.rst
- source/software/ssh_clients/Tectia/index.rst
- source/software/workflows/fre/index.rst
- source/systems/MSU-HPC_user_guide.rst
- source/systems/cloud_user_guide.rst
- source/systems/gaea_user_guide.rst
- source/systems/hera_user_guide.rst
- source/systems/jet_user_guide.rst
- source/systems/mercury_user_guide.rst
- source/systems/ppan_user_guide.rst
- source/systems/ursa_user_guide.rst
Per #551, this information was added.
I also removed ambiguous and hard-to-type characters from other pages across the site.
Thank you @laurenchilutti, @bensonr, @marshallward, and others for your input.
> Add dynamic linking information in the Gaea docs

- source/systems/cloud_user_guide.rst
User had some confusion over PW access requirements. We made the information clearer.
> Clarify PW list

- source/systems/MSU-HPC_user_guide.rst
Jim Sessner caught a typo in the sudo command, at line 1820
> corrected a typo spotted by a user
